# Generated by Django 6.0.5 on 2026-05-08 14:03

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_nascimento', models.DateField(help_text='Selecione a data de Nascimento', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Insira um CPF válido', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aula.pessoa')),
                ('email', models.EmailField(help_text='E-mail institucional do aluno', max_length=255, verbose_name='E-mail')),
                ('cod', models.CharField(help_text='Digite a matrícula do aluno', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Matrícula')),
            ],
            options={
                'abstract': False,
            },
            bases=('aula.pessoa',),
        ),
    ]
